import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { login } from '../services/authService';
import FadeIn from '../components/FadeIn';

function Login() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { const data = await login(email, password); localStorage.setItem('auth_token', data.token); navigate('/dashboard'); } catch (err) { setError(err.response?.data?.message || 'We could not sign you in.'); } finally { setLoading(false); } };
  return <main className="auth-page"><section className="auth-promo"><p className="eyebrow">LINKLY FOR EVERYONE</p><h1>Everything you share,<br/><span className="gradient-text">in its place.</span></h1><p>A calm, private home for your important files. Share in seconds, stay in control always.</p><div className="auth-chips"><span>◉ Private by default</span><span>↑ Up to 100 MB</span><span>⌁ Expiring links</span></div></section><FadeIn><section className="glass-card auth-card"><div className="auth-brand"><span className="brand-mark">↗</span> LINKLY</div><h2 className="auth-title">Welcome back</h2><p className="auth-subtitle">Sign in to your private library.</p><form onSubmit={submit}><label className="field-label">EMAIL ADDRESS</label><input required autoComplete="email" placeholder="you@example.com" type="email" value={email} onChange={e => setEmail(e.target.value)}/><label className="field-label">PASSWORD</label><div style={{position:'relative'}}><input required autoComplete="current-password" placeholder="Your password" type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} style={{paddingRight:72}}/><button type="button" className="secondary" onClick={() => setShowPassword(!showPassword)} style={{position:'absolute',right:6,top:6,padding:'7px 9px',fontSize:11}}>{showPassword ? 'Hide' : 'Show'}</button></div>{error && <p className="auth-error">{error}</p>}<button type="submit" disabled={loading} style={{width:'100%',marginTop:6}}>{loading ? 'Signing in…' : 'Continue →'}</button></form><p className="auth-foot">New to LINKLY? <Link to="/register">Create your account</Link></p></section></FadeIn></main>;
}
export default Login;
