import { useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { register } from '../services/authService';
import FadeIn from '../components/FadeIn';

function Register() {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const strength = useMemo(() => (password.length >= 12 ? 3 : password.length >= 8 ? 2 : password.length ? 1 : 0), [password]);
  const submit = async (event) => { event.preventDefault(); if (password !== confirmation) return setError('Passwords do not match.'); setError(''); setLoading(true); try { const data = await register(name, email, password, confirmation); localStorage.setItem('auth_token', data.token); navigate('/dashboard'); } catch (err) { setError(err.response?.data?.message || 'We could not create your account.'); } finally { setLoading(false); } };
  return <main className="auth-page"><section className="auth-promo"><p className="eyebrow">YOUR PRIVATE SPACE</p><h1>Start sharing<br/><span className="gradient-text">on your terms.</span></h1><p>Make beautiful share links, control when they expire, and keep your library organized from day one.</p><div className="auth-chips"><span>⌁ No clutter</span><span>◈ Every format</span><span>✦ Made for sharing</span></div></section><FadeIn><section className="glass-card auth-card"><div className="auth-brand"><span className="brand-mark">↗</span> LINKLY</div><h2 className="auth-title">Create account</h2><p className="auth-subtitle">Your private file library starts here.</p><form onSubmit={submit}><label className="field-label">DISPLAY NAME</label><input required placeholder="Your name" value={name} onChange={e => setName(e.target.value)}/><label className="field-label">EMAIL ADDRESS</label><input required type="email" autoComplete="email" placeholder="you@example.com" value={email} onChange={e => setEmail(e.target.value)}/><label className="field-label">PASSWORD</label><input required minLength="8" type="password" autoComplete="new-password" placeholder="At least 8 characters" value={password} onChange={e => setPassword(e.target.value)}/><div style={{display:'flex',gap:5,margin:'-8px 0 14px'}}>{[1,2,3].map(n => <i key={n} style={{height:4,flex:1,borderRadius:9,background:n <= strength ? '#63e6be' : 'rgba(255,255,255,.12)'}}/>)}</div><label className="field-label">CONFIRM PASSWORD</label><input required minLength="8" type="password" autoComplete="new-password" placeholder="Repeat your password" value={confirmation} onChange={e => setConfirmation(e.target.value)}/>{error && <p className="auth-error">{error}</p>}<button type="submit" disabled={loading} style={{width:'100%',marginTop:6}}>{loading ? 'Creating account…' : 'Create my library →'}</button></form><p className="auth-foot">Already have an account? <Link to="/login">Sign in</Link></p></section></FadeIn></main>;
}
export default Register;
